# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service_pb2 as service__pb2


class StorageServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Put = channel.unary_unary(
        '/tutorial.StorageService/Put',
        request_serializer=service__pb2.Value.SerializeToString,
        response_deserializer=service__pb2.Key.FromString,
        )
    self.Get = channel.unary_unary(
        '/tutorial.StorageService/Get',
        request_serializer=service__pb2.Key.SerializeToString,
        response_deserializer=service__pb2.Value.FromString,
        )


class StorageServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Put(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StorageServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Put': grpc.unary_unary_rpc_method_handler(
          servicer.Put,
          request_deserializer=service__pb2.Value.FromString,
          response_serializer=service__pb2.Key.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=service__pb2.Key.FromString,
          response_serializer=service__pb2.Value.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'tutorial.StorageService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
